FROM node:22.12-alpine AS builder

COPY * /
COPY tsconfig.json /tsconfig.json

WORKDIR /

RUN --mount=type=cache,target=/root/.npm npm install

RUN npx tsc --project tsconfig.json --outDir dist

FROM node:22-alpine AS release

WORKDIR /

COPY --from=builder /dist /dist
COPY --from=builder /package.json /package.json
COPY --from=builder /package-lock.json /package-lock.json

ENV NODE_ENV=production
ENV PORT=80

RUN npm ci --ignore-scripts --omit-dev

CMD ["node", "dist/server.js"]